// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file adapters/ios-backup/database/contact.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file adapters/ios-backup/database/contact.proto.
 */
export const file_adapters_ios_backup_database_contact: GenFile = /*@__PURE__*/
  fileDesc("CiphZGFwdGVycy9pb3MtYmFja3VwL2RhdGFiYXNlL2NvbnRhY3QucHJvdG8i8wEKD1dDQ29udGFjdFJlbWFyaxIVCghuaWNrbmFtZRgBIAEoCUgAiAEBEgoKAmlkGAIgASgJEhMKBnJlbWFyaxgDIAEoCUgBiAEBEhkKDHJlbWFya1BpbnlpbhgEIAEoCUgCiAEBEh4KEXJlbWFya1BpbnlpbkluaXRzGAUgASgJSAOIAQESGwoObmlja25hbWVQaW55aW4YBiABKAlIBIgBAUILCglfbmlja25hbWVCCQoHX3JlbWFya0IPCg1fcmVtYXJrUGlueWluQhQKEl9yZW1hcmtQaW55aW5Jbml0c0IRCg9fbmlja25hbWVQaW55aW4iagoSV0NDb250YWN0SGVhZEltYWdlEhsKDmhlYWRJbWFnZVRodW1iGAIgASgJSACIAQESFgoJaGVhZEltYWdlGAMgASgJSAGIAQFCEQoPX2hlYWRJbWFnZVRodW1iQgwKCl9oZWFkSW1hZ2UigQEKEFdDQ29udGFjdFByb2ZpbGUSEwoLcHJvZmlsZUZsYWcYASABKAUSFgoOcHJvZmlsZUNvdW50cnkYAiABKAkSFwoPcHJvZmlsZVByb3ZpbmNlGAMgASgJEhMKC3Byb2ZpbGVDaXR5GAQgASgJEhIKCnByb2ZpbGVCaW8YBSABKAkiVQoPV0NDb250YWN0U29jaWFsEhgKEHNvY2lhbEJhY2tncm91bmQYCSABKAkSGAoLc29jaWFsUGhvbmUYCyABKAlIAIgBAUIOCgxfc29jaWFsUGhvbmUilAEKEVdDQ29udGFjdENoYXRSb29tEhkKEWNoYXRyb29tTWVtYmVySWRzGAEgASgJEhgKEGNoYXRyb29tT3duZXJJZHMYAiABKAkSGQoRY2hhdHJvb21hTWF4Q291bnQYBCABKA0SFwoPY2hhdHJvb21WZXJzaW9uGAUgASgNEhYKDmNoYXRyb29tTWVtYmVyGAYgASgJIkUKD1dDQ29udGFjdE9wZW5JTRIZChFvcGVuSU1Db250YWN0SW5mbxgBIAEoCRIXCg9vcGVuSU1Db250YWN0SWQYAiABKAliBnByb3RvMw");

/**
 * @generated from message WCContactRemark
 */
export type WCContactRemark = Message<"WCContactRemark"> & {
  /**
   * @generated from field: optional string nickname = 1;
   */
  nickname?: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: optional string remark = 3;
   */
  remark?: string;

  /**
   * @generated from field: optional string remarkPinyin = 4;
   */
  remarkPinyin?: string;

  /**
   * @generated from field: optional string remarkPinyinInits = 5;
   */
  remarkPinyinInits?: string;

  /**
   * string field7 = 7;
   * string field8 = 8;
   *
   * @generated from field: optional string nicknamePinyin = 6;
   */
  nicknamePinyin?: string;
};

/**
 * Describes the message WCContactRemark.
 * Use `create(WCContactRemarkSchema)` to create a new message.
 */
export const WCContactRemarkSchema: GenMessage<WCContactRemark> = /*@__PURE__*/
  messageDesc(file_adapters_ios_backup_database_contact, 0);

/**
 * @generated from message WCContactHeadImage
 */
export type WCContactHeadImage = Message<"WCContactHeadImage"> & {
  /**
   * int32 headImageFlag = 1; // 我不知道我怎么知道这个字段叫 flag 以及有什么用
   *
   * @generated from field: optional string headImageThumb = 2;
   */
  headImageThumb?: string;

  /**
   * string field4 = 4;
   *
   * @generated from field: optional string headImage = 3;
   */
  headImage?: string;
};

/**
 * Describes the message WCContactHeadImage.
 * Use `create(WCContactHeadImageSchema)` to create a new message.
 */
export const WCContactHeadImageSchema: GenMessage<WCContactHeadImage> = /*@__PURE__*/
  messageDesc(file_adapters_ios_backup_database_contact, 1);

/**
 * @generated from message WCContactProfile
 */
export type WCContactProfile = Message<"WCContactProfile"> & {
  /**
   * 我不知道我怎么知道这个字段叫 flag 以及有什么用
   *
   * @generated from field: int32 profileFlag = 1;
   */
  profileFlag: number;

  /**
   * @generated from field: string profileCountry = 2;
   */
  profileCountry: string;

  /**
   * @generated from field: string profileProvince = 3;
   */
  profileProvince: string;

  /**
   * @generated from field: string profileCity = 4;
   */
  profileCity: string;

  /**
   * @generated from field: string profileBio = 5;
   */
  profileBio: string;
};

/**
 * Describes the message WCContactProfile.
 * Use `create(WCContactProfileSchema)` to create a new message.
 */
export const WCContactProfileSchema: GenMessage<WCContactProfile> = /*@__PURE__*/
  messageDesc(file_adapters_ios_backup_database_contact, 2);

/**
 * @generated from message WCContactSocial
 */
export type WCContactSocial = Message<"WCContactSocial"> & {
  /**
   * string field1 = 1;
   * string field2 = 2;
   * int32 field3 = 3;
   * int32 field7 = 7;
   * int32 field8 = 8;
   *
   * @generated from field: string socialBackground = 9;
   */
  socialBackground: string;

  /**
   * string field10 = 10;
   *
   * string field12 = 12;
   *
   * @generated from field: optional string socialPhone = 11;
   */
  socialPhone?: string;
};

/**
 * Describes the message WCContactSocial.
 * Use `create(WCContactSocialSchema)` to create a new message.
 */
export const WCContactSocialSchema: GenMessage<WCContactSocial> = /*@__PURE__*/
  messageDesc(file_adapters_ios_backup_database_contact, 3);

/**
 * @generated from message WCContactChatRoom
 */
export type WCContactChatRoom = Message<"WCContactChatRoom"> & {
  /**
   * @generated from field: string chatroomMemberIds = 1;
   */
  chatroomMemberIds: string;

  /**
   * @generated from field: string chatroomOwnerIds = 2;
   */
  chatroomOwnerIds: string;

  /**
   * 这应该也是我猜的
   *
   * @generated from field: uint32 chatroomaMaxCount = 4;
   */
  chatroomaMaxCount: number;

  /**
   * 我不知道我为什么知道这个字段叫 version
   *
   * @generated from field: uint32 chatroomVersion = 5;
   */
  chatroomVersion: number;

  /**
   * xml
   *
   * @generated from field: string chatroomMember = 6;
   */
  chatroomMember: string;
};

/**
 * Describes the message WCContactChatRoom.
 * Use `create(WCContactChatRoomSchema)` to create a new message.
 */
export const WCContactChatRoomSchema: GenMessage<WCContactChatRoom> = /*@__PURE__*/
  messageDesc(file_adapters_ios_backup_database_contact, 4);

/**
 * @generated from message WCContactOpenIM
 */
export type WCContactOpenIM = Message<"WCContactOpenIM"> & {
  /**
   * json
   *
   * @generated from field: string openIMContactInfo = 1;
   */
  openIMContactInfo: string;

  /**
   * @generated from field: string openIMContactId = 2;
   */
  openIMContactId: string;
};

/**
 * Describes the message WCContactOpenIM.
 * Use `create(WCContactOpenIMSchema)` to create a new message.
 */
export const WCContactOpenIMSchema: GenMessage<WCContactOpenIM> = /*@__PURE__*/
  messageDesc(file_adapters_ios_backup_database_contact, 5);

