// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file schema/open-message-red-envelope-cover-info.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file schema/open-message-red-envelope-cover-info.proto.
 */
export const file_schema_open_message_red_envelope_cover_info: GenFile = /*@__PURE__*/
  fileDesc("CjFzY2hlbWEvb3Blbi1tZXNzYWdlLXJlZC1lbnZlbG9wZS1jb3Zlci1pbmZvLnByb3RvIqUECh9PcGVuTWVzc2FnZVJlZEVudmVsb3BlQ292ZXJJbmZvEhcKD29wZW5pbmdJbWFnZVVybBgFIAEoCRIXCg9vcGVuaW5nSW1hZ2VNZDUYBiABKAkSFgoOZGV0YWlsSW1hZ2VVcmwYByABKAkSEwoLcmVkUGFja2V0SWQYCiABKAkSFAoHZmllbGQxMhgMIAEoCUgAiAEBEiYKGW9wZW5pbmdEZWNvcmF0aW9uSW1hZ2VVcmwYECABKAlIAYgBARIrCh5idWJibGVEZWNvcmF0aW9uU2VuZGVySW1hZ2VVcmwYEiABKAlIAogBARItCiBidWJibGVEZWNvcmF0aW9uUmVjZWl2ZXJJbWFnZVVybBgUIAEoCUgDiAEBEhQKB2ZpZWxkMjQYGCABKAlIBIgBARIUCgdmaWVsZDI4GBwgASgJSAWIAQESFAoHZmllbGQzMBgeIAEoCUgGiAEBEg8KB2ZpZWxkMzIYICABKAUSFAoHZmllbGQzMxghIAEoCUgHiAEBQgoKCF9maWVsZDEyQhwKGl9vcGVuaW5nRGVjb3JhdGlvbkltYWdlVXJsQiEKH19idWJibGVEZWNvcmF0aW9uU2VuZGVySW1hZ2VVcmxCIwohX2J1YmJsZURlY29yYXRpb25SZWNlaXZlckltYWdlVXJsQgoKCF9maWVsZDI0QgoKCF9maWVsZDI4QgoKCF9maWVsZDMwQgoKCF9maWVsZDMzYgZwcm90bzM");

/**
 * @generated from message OpenMessageRedEnvelopeCoverInfo
 */
export type OpenMessageRedEnvelopeCoverInfo = Message<"OpenMessageRedEnvelopeCoverInfo"> & {
  /**
   * 拆红包页图片
   *
   * @generated from field: string openingImageUrl = 5;
   */
  openingImageUrl: string;

  /**
   * 拆红包页图片md5
   *
   * @generated from field: string openingImageMd5 = 6;
   */
  openingImageMd5: string;

  /**
   * 也许是红包详情页，相比于第五字段的图片，底下没有红色装饰
   *
   * @generated from field: string detailImageUrl = 7;
   */
  detailImageUrl: string;

  /**
   * `redpacketid_${string}`
   *
   * @generated from field: string redPacketId = 10;
   */
  redPacketId: string;

  /**
   * 品牌logo
   *
   * @generated from field: optional string field12 = 12;
   */
  field12?: string;

  /**
   * 拆红包页红包挂件图片
   *
   * @generated from field: optional string openingDecorationImageUrl = 16;
   */
  openingDecorationImageUrl?: string;

  /**
   * 拆红包页红包挂件图片，猜测和字段20一个是发送方一个是接收方
   *
   * @generated from field: optional string bubbleDecorationSenderImageUrl = 18;
   */
  bubbleDecorationSenderImageUrl?: string;

  /**
   * 拆红包页红包挂件图片，猜测和字段20一个是发送方一个是接收方
   *
   * @generated from field: optional string bubbleDecorationReceiverImageUrl = 20;
   */
  bubbleDecorationReceiverImageUrl?: string;

  /**
   * 品牌logo
   *
   * @generated from field: optional string field24 = 24;
   */
  field24?: string;

  /**
   * 品牌logo
   *
   * @generated from field: optional string field28 = 28;
   */
  field28?: string;

  /**
   * 品牌logo
   *
   * @generated from field: optional string field30 = 30;
   */
  field30?: string;

  /**
   * 0/1 
   *
   * @generated from field: int32 field32 = 32;
   */
  field32: number;

  /**
   * 未知，看上去和气泡图片一样
   *
   * @generated from field: optional string field33 = 33;
   */
  field33?: string;
};

/**
 * Describes the message OpenMessageRedEnvelopeCoverInfo.
 * Use `create(OpenMessageRedEnvelopeCoverInfoSchema)` to create a new message.
 */
export const OpenMessageRedEnvelopeCoverInfoSchema: GenMessage<OpenMessageRedEnvelopeCoverInfo> = /*@__PURE__*/
  messageDesc(file_schema_open_message_red_envelope_cover_info, 0);

